(()=>{if(globalThis.__quickSubmitLoaded)return;globalThis.__quickSubmitLoaded=true;
let mode=null,slotIndex=null,current=null,box=null,tip=null,noticeTimer=null;
const visible=e=>{if(!(e instanceof HTMLElement))return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};
const clean=v=>String(v||"").replace(/\s+/g," ").trim().slice(0,80);
function ui(){box=document.getElementById("quick-submit-highlight")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"quick-submit-highlight"}));tip=document.getElementById("quick-submit-tooltip")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"quick-submit-tooltip"}));}
function selector(e){if(e.id){const q="#"+CSS.escape(e.id);if(document.querySelectorAll(q).length===1)return q;}const name=e.getAttribute("name");if(name){const q=e.tagName.toLowerCase()+"[name=\""+CSS.escape(name)+"\"]";try{if(document.querySelectorAll(q).length===1)return q;}catch{}}const parts=[];let n=e;while(n&&n!==document.documentElement){let p=n.tagName.toLowerCase();const siblings=n.parentElement?[...n.parentElement.children].filter(x=>x.tagName===n.tagName):[];if(siblings.length>1)p+=`:nth-of-type(${siblings.indexOf(n)+1})`;parts.unshift(p);const q=parts.join(" > ");if(document.querySelectorAll(q).length===1)return q;n=n.parentElement;}return "";}
function label(e){if(e.labels?.length)return clean(e.labels[0].textContent);return clean(e.getAttribute("aria-label")||e.getAttribute("title")||e.getAttribute("placeholder")||e.getAttribute("name")||e.textContent)||"未命名元素";}
function kind(e){if(e instanceof HTMLSelectElement)return "select";if(e instanceof HTMLTextAreaElement)return "text";if(e instanceof HTMLInputElement){const t=(e.type||"text").toLowerCase();if(["text","email","number","tel","url","search"].includes(t))return t==="number"?"number":"text";}if(e instanceof HTMLButtonElement)return "button";return null;}
function candidate(start,submit){const q=submit?'button,input[type="button"],input[type="submit"]':'input,textarea,select,button';const e=start instanceof Element?start.closest(q):null;if(!e||!visible(e)||e.disabled)return null;const k=kind(e);if(submit)return (e instanceof HTMLButtonElement||["button","submit"].includes(e.type))?e:null;if(k==="button"){const sig=clean([e.getAttribute("aria-label"),e.title,e.textContent,e.className].join(" ")).toLowerCase();if(/(^|\s|icon-|fa-|mdi-)(plus|minus)(\s|$)|增加|減少|加號|減號|^\+$|^-$/.test(sig))return e;return null;}return k?e:null;}
function position(e,text,color="#0f6cbd"){ui();current=e;const r=e.getBoundingClientRect();box.style.cssText+=`;left:${r.left-3}px;top:${r.top-3}px;width:${r.width+6}px;height:${r.height+6}px;display:block;border-color:${color}`;tip.textContent=text;tip.style.display="block";tip.style.background=color;requestAnimationFrame(()=>{const tr=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.left,innerWidth-tr.width-8))+"px";tip.style.top=(r.top-tr.height-8>8?r.top-tr.height-8:r.bottom+8)+"px";});}
function hide(){current=null;if(box)box.style.display="none";if(tip)tip.style.display="none";}
function stop(send=true){document.removeEventListener("mousemove",move,true);document.removeEventListener("click",click,true);document.removeEventListener("keydown",key,true);hide();const old=mode;mode=null;slotIndex=null;if(send&&old)chrome.runtime.sendMessage({type:"SELECTION_CANCELLED"}).catch(()=>{});}
function move(ev){const e=candidate(ev.target,mode==="submit");if(e)position(e,(mode==="submit"?"送出按鈕｜":"操作元素｜")+label(e),mode==="submit"?"#8764b8":"#0f6cbd");else hide();}
function click(ev){const e=candidate(ev.target,mode==="submit");if(!e)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();const s=selector(e);if(!s){position(e,"無法建立唯一定位","#a4262c");return;}const k=kind(e);const data={id:crypto.randomUUID(),name:label(e),kind:k,selector:s,pageUrl:location.href,options:k==="select"?[...e.options].map(o=>({value:o.value,text:clean(o.textContent)})):[]};if(k==="button"){const sig=clean([e.getAttribute("aria-label"),e.title,e.textContent,e.className].join(" ")).toLowerCase();data.kind=/minus|減少|減號|^-$/i.test(sig)?"decrement":"increment";}const type=mode==="submit"?"SUBMIT_SELECTED":"OPERATION_SELECTED";const index=slotIndex;stop(false);chrome.runtime.sendMessage({type,payload:{...data,slotIndex:index}}).catch(()=>{});}
function key(ev){if(ev.key==="Escape")stop(true);}
function start(nextMode,index){stop(false);mode=nextMode;slotIndex=index;ui();document.addEventListener("mousemove",move,true);document.addEventListener("click",click,true);document.addEventListener("keydown",key,true);}
function find(loc){let m;try{m=document.querySelectorAll(loc.selector);}catch{return{status:"invalid-selector"};}if(m.length!==1)return{status:m.length?"multiple":"not-found",matchCount:m.length};return{status:"valid",element:m[0],matchCount:1};}
function setValue(e,v){const proto=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const d=Object.getOwnPropertyDescriptor(proto,"value");d?.set?d.set.call(e,String(v)):e.value=String(v);e.dispatchEvent(new Event("input",{bubbles:true,composed:true}));e.dispatchEvent(new Event("change",{bubbles:true,composed:true}));}
async function execute(op,value,executionId){const f=find(op);if(f.status!=="valid")return{status:f.status,matchCount:f.matchCount};const e=f.element;if(!visible(e)||e.disabled)return{status:"unavailable"};if(op.kind==="text"||op.kind==="number"){setValue(e,value);return{status:e.value===String(value)?"success":"mismatch"};}if(op.kind==="select"){const option=[...e.options].find(o=>o.value===value)||[...e.options].find(o=>clean(o.textContent)===value);if(!option)return{status:"option-not-found"};e.value=option.value;e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));return{status:e.value===option.value?"success":"mismatch"};}if(op.kind==="increment"||op.kind==="decrement"){const count=Number(value);if(!Number.isInteger(count)||count<0||count>50)return{status:"invalid-count"};for(let i=0;i<count;i++){const again=find(op);if(again.status!=="valid"||!visible(again.element)||again.element.disabled)return{status:"button-unavailable",completedCount:i};again.element.click();await new Promise(r=>setTimeout(r,120));}return{status:"success",completedCount:count};}return{status:"unsupported"};}
function focusSubmit(submit){const f=find(submit);if(f.status!=="valid")return{status:f.status,matchCount:f.matchCount};const e=f.element;if(!visible(e)||e.disabled)return{status:"unavailable"};e.scrollIntoView({behavior:"smooth",block:"center",inline:"center"});setTimeout(()=>{position(e,"送出按鈕｜"+label(e),"#8764b8");try{e.focus({preventScroll:true});}catch{}document.getElementById("quick-submit-focus-notice")?.remove();const n=document.createElement("div");n.id="quick-submit-focus-notice";n.textContent="已跳到送出按鈕。若鍵盤焦點仍在側邊欄，請按 F6 切換到網頁，再按 Enter 或 Space。";document.body.appendChild(n);clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.remove(),15000);setTimeout(()=>{if(current===e)hide();},3000);},300);return{status:"focused"};}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m.type==="START_OPERATION_SELECTION"){start("operation",m.slotIndex);reply({success:true});return;}if(m.type==="START_SUBMIT_SELECTION"){start("submit",null);reply({success:true});return;}if(m.type==="STOP_SELECTION"){stop(false);reply({success:true});return;}if(m.type==="TEST_LOCATOR"){const f=find(m.locator);if(f.status==="valid")position(f.element,"定位有效｜"+label(f.element),"#107c10");reply({success:true,result:{status:f.status,matchCount:f.matchCount}});return;}if(m.type==="EXECUTE_OPERATION"){execute(m.operation,m.value,m.executionId).then(result=>reply({success:true,result}));return true;}if(m.type==="FOCUS_SUBMIT"){reply({success:true,result:focusSubmit(m.submit)});return;}});
})();
