(()=>{if(globalThis.__quickSubmitLoaded)return;globalThis.__quickSubmitLoaded=true;
let mode=null,slotIndex=null,current=null,box=null,tip=null,overlay=null,noticeTimer=null,highlightTimer=null;
const clean=v=>String(v||"").replace(/\s+/g," ").trim().slice(0,80);
const visible=e=>{if(!(e instanceof HTMLElement))return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};
function ui(){box=document.getElementById("quick-submit-highlight")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"quick-submit-highlight"}));tip=document.getElementById("quick-submit-tooltip")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"quick-submit-tooltip"}));}
function selector(e){if(e.id){const q="#"+CSS.escape(e.id);if(document.querySelectorAll(q).length===1)return q;}const stable=["data-testid","data-test","data-cy","name"];for(const a of stable){const v=e.getAttribute(a);if(v){const q=e.tagName.toLowerCase()+`[${a}="${CSS.escape(v)}"]`;try{if(document.querySelectorAll(q).length===1)return q;}catch{}}}const parts=[];let n=e;while(n&&n!==document.documentElement){let p=n.tagName.toLowerCase();const cls=[...n.classList].filter(x=>!/^v-|disabled|active|focus|hover|elevation/.test(x)).slice(0,2);if(cls.length)p+="."+cls.map(CSS.escape).join(".");const siblings=n.parentElement?[...n.parentElement.children].filter(x=>x.tagName===n.tagName):[];if(siblings.length>1)p+=`:nth-of-type(${siblings.indexOf(n)+1})`;parts.unshift(p);const q=parts.join(" > ");try{if(document.querySelectorAll(q).length===1)return q;}catch{}n=n.parentElement;}return "";}
function label(e){if(e.labels?.length)return clean(e.labels[0].textContent);return clean(e.getAttribute("aria-label")||e.getAttribute("title")||e.getAttribute("placeholder")||e.getAttribute("name")||e.textContent)||"未命名元素";}
function kind(e){if(e instanceof HTMLSelectElement)return"select";if(e instanceof HTMLTextAreaElement)return"text";if(e instanceof HTMLInputElement){const t=(e.type||"text").toLowerCase();if(["text","email","number","tel","url","search"].includes(t))return t==="number"?"number":"text";if(["button","submit"].includes(t))return"button";}if(e instanceof HTMLButtonElement||e.getAttribute?.("role")==="button")return"button";return null;}
function isButton(e){return e instanceof HTMLButtonElement||(e instanceof HTMLInputElement&&["button","submit"].includes(e.type))||e.getAttribute?.("role")==="button";}
function candidateFromPoint(x,y,submit){if(overlay)overlay.style.pointerEvents="none";const stack=document.elementsFromPoint(x,y);if(overlay)overlay.style.pointerEvents="auto";const query=submit?'button,input[type="button"],input[type="submit"],[role="button"]':'input,textarea,select,button,[role="button"]';for(const raw of stack){const e=raw.closest?.(query);if(!e||e===overlay||!visible(e))continue;if(submit){if(isButton(e))return e;continue;}const k=kind(e);if(!k)continue;if(k!=="button"&&(e.disabled||e.getAttribute("aria-disabled")==="true"))continue;return e;}return null;}
function position(e,text,color="#0f6cbd"){ui();current=e;const r=e.getBoundingClientRect();Object.assign(box.style,{left:`${r.left-3}px`,top:`${r.top-3}px`,width:`${r.width+6}px`,height:`${r.height+6}px`,display:"block",borderColor:color});tip.textContent=text;tip.style.display="block";tip.style.background=color;requestAnimationFrame(()=>{const tr=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.left,innerWidth-tr.width-8))+"px";tip.style.top=(r.top-tr.height-8>8?r.top-tr.height-8:r.bottom+8)+"px";});}
function hide(){current=null;if(box)box.style.display="none";if(tip)tip.style.display="none";}
function removeOverlay(){overlay?.remove();overlay=null;}
function stop(send=true){removeOverlay();hide();const old=mode;mode=null;slotIndex=null;if(send&&old)chrome.runtime.sendMessage({type:"SELECTION_CANCELLED"}).catch(()=>{});}
function buttonKind(e){const childSig=[...e.querySelectorAll("i,span,svg,use")].map(n=>[n.className?.baseVal||n.className||"",n.getAttribute("href")||"",n.getAttribute("xlink:href")||"",n.getAttribute("data-icon")||""].join(" ")).join(" ");const sig=clean([e.getAttribute("aria-label"),e.title,e.getAttribute("data-action"),e.getAttribute("data-testid"),e.textContent,e.className,childSig].join(" ")).toLowerCase();return /(^|[^a-z])(minus|remove|decrement|subtract)([^a-z]|$)|減少|減號|扣除|^-$/.test(sig)?"decrement":"increment";}
function selectAt(x,y){if(!mode)return;const e=candidateFromPoint(x,y,mode==="submit");if(!e)return;const s=selector(e);if(!s){position(e,"無法建立唯一定位","#a4262c");return;}let k=kind(e);const data={id:crypto.randomUUID(),name:label(e),kind:k,selector:s,pageUrl:location.href,disabledAtSelection:Boolean(e.disabled||e.getAttribute("aria-disabled")==="true"),options:k==="select"?[...e.options].map(o=>({value:o.value,text:clean(o.textContent)})):[]};if(k==="button")data.kind=buttonKind(e);const type=mode==="submit"?"SUBMIT_SELECTED":"OPERATION_SELECTED";const index=slotIndex;stop(false);chrome.runtime.sendMessage({type,payload:{...data,slotIndex:index}}).catch(()=>{});}
function createOverlay(){removeOverlay();overlay=document.createElement("div");overlay.id="quick-submit-selection-overlay";overlay.tabIndex=0;overlay.setAttribute("aria-label","框選模式，按 Escape 取消");overlay.addEventListener("pointermove",ev=>{const e=candidateFromPoint(ev.clientX,ev.clientY,mode==="submit");if(e)position(e,(mode==="submit"?"送出按鈕｜":"操作元素｜")+label(e),mode==="submit"?"#8764b8":"#0f6cbd");else hide();});overlay.addEventListener("pointerdown",ev=>{ev.preventDefault();ev.stopPropagation();selectAt(ev.clientX,ev.clientY);},{capture:true});overlay.addEventListener("keydown",ev=>{if(ev.key==="Escape"){ev.preventDefault();stop(true);}});overlay.addEventListener("wheel",ev=>{overlay.style.pointerEvents="none";const below=document.elementFromPoint(ev.clientX,ev.clientY);overlay.style.pointerEvents="auto";below?.dispatchEvent(new WheelEvent("wheel",{deltaX:ev.deltaX,deltaY:ev.deltaY,deltaMode:ev.deltaMode,bubbles:true,cancelable:true}));},{passive:false});document.documentElement.appendChild(overlay);overlay.focus({preventScroll:true});}
function start(nextMode,index){stop(false);mode=nextMode;slotIndex=index;ui();createOverlay();}
function find(loc){let m;try{m=document.querySelectorAll(loc.selector);}catch{return{status:"invalid-selector"};}if(m.length!==1)return{status:m.length?"multiple":"not-found",matchCount:m.length};return{status:"valid",element:m[0],matchCount:1};}
function locatorState(loc){const f=find(loc);if(f.status!=="valid")return{status:f.status,matchCount:f.matchCount};return{status:"valid",matchCount:1,disabled:Boolean(f.element.disabled||f.element.getAttribute("aria-disabled")==="true"),visible:visible(f.element)};}
function setValue(e,v){const proto=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const d=Object.getOwnPropertyDescriptor(proto,"value");d?.set?d.set.call(e,String(v)):e.value=String(v);e.dispatchEvent(new Event("input",{bubbles:true,composed:true}));e.dispatchEvent(new Event("change",{bubbles:true,composed:true}));}
async function execute(op,value){const f=find(op);if(f.status!=="valid")return{status:f.status,matchCount:f.matchCount};const e=f.element;if(!visible(e)||e.disabled)return{status:"unavailable"};if(op.kind==="text"||op.kind==="number"){setValue(e,value);return{status:e.value===String(value)?"success":"mismatch"};}if(op.kind==="select"){const option=[...e.options].find(o=>o.value===value)||[...e.options].find(o=>clean(o.textContent)===value);if(!option)return{status:"option-not-found"};e.value=option.value;e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));return{status:e.value===option.value?"success":"mismatch"};}if(op.kind==="increment"||op.kind==="decrement"){const count=Number(value);if(!Number.isInteger(count)||count<0||count>50)return{status:"invalid-count"};for(let i=0;i<count;i++){const again=find(op);if(again.status!=="valid"||!visible(again.element)||again.element.disabled)return{status:"button-unavailable",completedCount:i};again.element.click();await new Promise(r=>setTimeout(r,120));}return{status:"success",completedCount:count};}return{status:"unsupported"};}
async function waitForSubmit(submit,timeoutMs=2500){const end=Date.now()+timeoutMs;let state;do{state=locatorState(submit);if(state.status==="valid"&&state.visible&&!state.disabled)return state;await new Promise(r=>setTimeout(r,100));}while(Date.now()<end);return state||{status:"not-found"};}
async function focusSubmit(submit,waitForEnable=false){const state=waitForEnable?await waitForSubmit(submit):locatorState(submit);if(state.status!=="valid")return state;if(!state.visible)return{status:"unavailable"};if(state.disabled)return{status:"disabled"};const e=find(submit).element;e.scrollIntoView({behavior:"smooth",block:"center",inline:"center"});setTimeout(()=>{position(e,"送出按鈕｜"+label(e),"#8764b8");try{e.focus({preventScroll:true});}catch{}document.getElementById("quick-submit-focus-notice")?.remove();const n=document.createElement("div");n.id="quick-submit-focus-notice";n.textContent="已跳到送出按鈕。若鍵盤焦點仍在側邊欄，請按 F6 切換到網頁，再按 Enter 或 Space。";document.body.appendChild(n);clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.remove(),15000);clearTimeout(highlightTimer);highlightTimer=setTimeout(()=>{if(current===e)hide();},3000);},300);return{status:"focused"};}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m.type==="PING"){reply({success:true});return;}if(m.type==="START_OPERATION_SELECTION"){start("operation",m.slotIndex);reply({success:true});return;}if(m.type==="START_SUBMIT_SELECTION"){start("submit",null);reply({success:true});return;}if(m.type==="STOP_SELECTION"){stop(false);reply({success:true});return;}if(m.type==="TEST_LOCATOR"){const result=locatorState(m.locator);if(result.status==="valid"){const e=find(m.locator).element;position(e,(result.disabled?"定位有效，但目前停用｜":"定位有效｜")+label(e),result.disabled?"#d83b01":"#107c10");}reply({success:true,result});return;}if(m.type==="EXECUTE_OPERATION"){execute(m.operation,m.value).then(result=>reply({success:true,result}));return true;}if(m.type==="FOCUS_SUBMIT"){focusSubmit(m.submit,Boolean(m.waitForEnable)).then(result=>reply({success:true,result}));return true;}});
})();
