const $=id=>document.getElementById(id);const PROFILE_KEY="quickSubmitProfiles";const SLOT_COUNT=5;
let target=null,profile=null,busy=false,selecting=null,saveTimer=null;
const emptyProfile=key=>({pageKey:key,operations:Array.from({length:SLOT_COUNT},(_,i)=>({slot:i,element:null,value:""})),submit:null,updatedAt:new Date().toISOString()});
const pageKey=url=>{try{const u=new URL(url);return u.origin+u.pathname;}catch{return null;}};
async function activeTab(){return(await chrome.tabs.query({active:true,currentWindow:true}))[0];}
async function ensureContent(tabId){try{const r=await chrome.tabs.sendMessage(tabId,{type:"PING"});if(r)return;}catch{}try{await chrome.scripting.insertCSS({target:{tabId},files:["content-style.css"]});}catch{}try{await chrome.scripting.executeScript({target:{tabId},files:["content-script.js"]});}catch(e){if(!String(e.message).includes("already"))throw e;}}
async function loadTarget(){const r=await chrome.runtime.sendMessage({type:"GET_TARGET"});target=r.target||null;await loadProfile();render();}
async function loadProfile(){if(!target){profile=null;return;}const r=await chrome.storage.local.get(PROFILE_KEY),all=r[PROFILE_KEY]||{};profile=all[target.pageKey]||emptyProfile(target.pageKey);while(profile.operations.length<SLOT_COUNT)profile.operations.push({slot:profile.operations.length,element:null,value:""});}
async function saveProfile(){if(!profile)return;profile.updatedAt=new Date().toISOString();const r=await chrome.storage.local.get(PROFILE_KEY),all=r[PROFILE_KEY]||{};all[profile.pageKey]=profile;await chrome.storage.local.set({[PROFILE_KEY]:all});}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveProfile().catch(showError),300);}
function targetReady(){return !!(target&&target.status==="active"&&profile);}
function setupComplete(){return targetReady()&&profile.operations.some(x=>x.element)&&profile.submit;}
function typeName(k){return({text:"文字框",number:"數字框",select:"下拉選單",increment:"增加按鈕",decrement:"減少按鈕"})[k]||k;}
function status(el,text,kind=""){el.textContent=text;el.className="status"+(kind?" "+kind:"");}
function render(){const ready=targetReady();$("targetSummary").textContent=target?`${target.title||"未命名頁面"}｜${target.status==="active"?"就緒":"頁面已變更"}`:"尚未設定目標網頁";$("targetBadge").textContent=ready?"已設定":"未設定";$("targetBadge").className="badge "+(ready?"success":"idle");$("targetDetails").textContent=target?`${target.origin}${target.pathname}`:"使用目前分頁建立設定。";$("clearTargetButton").disabled=!target||busy;$("setupBadge").textContent=setupComplete()?"已完成":"未完成";$("setupBadge").className="badge "+(setupComplete()?"success":"idle");$("readyBadge").textContent=setupComplete()?"就緒":"未就緒";$("readyBadge").className="badge "+(setupComplete()?"success":"idle");$("submitBadge").textContent=profile?.submit?"已設定":"未設定";$("submitBadge").className="badge "+(profile?.submit?"success":"idle");$("submitDetails").textContent=profile?.submit?`${profile.submit.name}｜${profile.submit.selector}`:"尚未框選送出按鈕。";$("refreshPageButton").disabled=!targetReady()||busy;$("focusSubmitButton").disabled=!targetReady()||!profile?.submit||busy;$("selectSubmitButton").disabled=!ready||busy;$("testSubmitButton").disabled=!ready||!profile?.submit||busy;$("finishSetupButton").disabled=!setupComplete()||busy;$("cancelSelectionButton").hidden=!selecting;$("cancelSelectionButton").disabled=!selecting;renderOperations();renderSetupRows();}
function valueControl(item,index){const e=item.element;let c;if(e?.kind==="select"){c=document.createElement("select");c.className="value-select";const blank=document.createElement("option");blank.value="";blank.textContent="請選擇";c.append(blank);(e.options||[]).forEach(o=>{const x=document.createElement("option");x.value=o.value;x.textContent=o.text||o.value;x.selected=item.value===o.value;c.append(x);});}else{c=document.createElement("input");c.className="value-input";c.type=["number","increment","decrement"].includes(e?.kind)?"number":"text";if(["increment","decrement"].includes(e?.kind)){c.min="0";c.max="50";c.step="1";c.placeholder="次數 0-50";}else c.placeholder=e?"輸入內容值":"尚未設定元素";c.value=item.value||"";}c.disabled=!e||busy;c.setAttribute("aria-label",`第 ${index+1} 組內容值`);c.addEventListener("input",ev=>{item.value=ev.target.value;scheduleSave();});c.addEventListener("change",ev=>{item.value=ev.target.value;scheduleSave();});return c;}
function renderOperations(){const list=$("operationList");list.replaceChildren();const rows=profile?.operations||Array.from({length:SLOT_COUNT},(_,i)=>({slot:i,element:null,value:""}));rows.slice(0,SLOT_COUNT).forEach((item,i)=>{const row=document.createElement("div");row.className="operation-row";const seq=document.createElement("span");seq.className="sequence";seq.textContent=i+1;const main=document.createElement("div");main.className="operation-main";const name=document.createElement("strong");name.className="operation-name";name.textContent=item.element?`${item.element.name}｜${typeName(item.element.kind)}`:"尚未設定";main.append(name,valueControl(item,i));const b=document.createElement("button");b.className="row-button";b.type="button";b.textContent=item.element?"執行並轉跳":"前往設定";b.disabled=busy||(!item.element&&!targetReady());b.addEventListener("click",()=>item.element?executeOne(i):startSelectOperation(i));row.append(seq,main,b);list.append(row);});}
function renderSetupRows(){const list=$("slotSetupList");list.replaceChildren();const rows=profile?.operations||Array.from({length:SLOT_COUNT},(_,i)=>({slot:i,element:null,value:""}));rows.slice(0,SLOT_COUNT).forEach((item,i)=>{const row=document.createElement("div");row.className="setup-row";const seq=document.createElement("span");seq.className="sequence";seq.textContent=i+1;const info=document.createElement("div");info.className="setup-row-info";const name=document.createElement("strong");name.className="setup-row-name";name.textContent=item.element?item.element.name:"尚未設定";const type=document.createElement("span");type.className="setup-row-type";type.textContent=item.element?typeName(item.element.kind):"請框選目標網頁元素";const acts=document.createElement("div");acts.className="setup-row-actions";const select=button(item.element?"重選":"框選",()=>startSelectOperation(i),!targetReady()||busy);const test=button("測試",()=>testLocator(item.element),!item.element||busy);const del=button("清除",()=>clearOperation(i),!item.element||busy);acts.append(select,test,del);info.append(name,type,acts);row.append(seq,info);list.append(row);});}
function button(text,fn,disabled){const b=document.createElement("button");b.type="button";b.textContent=text;b.disabled=disabled;b.addEventListener("click",fn);return b;}

async function cancelSelection(){
  if(!selecting)return;
  try{if(target?.tabId)await chrome.tabs.sendMessage(target.tabId,{type:"STOP_SELECTION"});}catch{}
  busy=false;selecting=null;render();status($("setupStatus"),"已取消框選，可重新選擇元素。");
}
async function setTarget(){try{const tab=await activeTab();const r=await chrome.runtime.sendMessage({type:"SET_TARGET",tabId:tab.id});if(!r.success)throw Error(r.error);target=r.target;await loadProfile();status($("setupStatus"),"已設定目前分頁為目標網頁。","success");render();}catch(e){showError(e);}}
async function clearTarget(){await chrome.runtime.sendMessage({type:"CLEAR_TARGET"});target=null;profile=null;render();status($("setupStatus"),"已清除目前目標，已保存的頁面設定仍保留。");}
async function startSelectOperation(index){if(!targetReady())return;try{busy=true;selecting={type:"operation",index};render();await ensureContent(target.tabId);await chrome.tabs.sendMessage(target.tabId,{type:"START_OPERATION_SELECTION",slotIndex:index});await chrome.windows.update((await chrome.tabs.get(target.tabId)).windowId,{focused:true});await chrome.tabs.update(target.tabId,{active:true});status($("setupStatus"),`請到目標網頁框選第 ${index+1} 組元素，按 Esc 可取消。`);}catch(e){busy=false;selecting=null;showError(e);render();}}
async function startSelectSubmit(){if(!targetReady())return;try{busy=true;selecting={type:"submit"};render();await ensureContent(target.tabId);await chrome.tabs.sendMessage(target.tabId,{type:"START_SUBMIT_SELECTION"});await chrome.windows.update((await chrome.tabs.get(target.tabId)).windowId,{focused:true});await chrome.tabs.update(target.tabId,{active:true});status($("setupStatus"),"請到目標網頁框選送出按鈕，按 Esc 可取消。");}catch(e){busy=false;selecting=null;showError(e);render();}}
async function testLocator(locator){try{busy=true;render();await ensureContent(target.tabId);const r=await chrome.tabs.sendMessage(target.tabId,{type:"TEST_LOCATOR",locator});const ok=r?.result?.status==="valid";const disabled=ok&&r.result.disabled;status($("setupStatus"),ok?(disabled?"定位有效，但元素目前為停用狀態。":"定位測試成功，唯一找到 1 個元素。"):`定位測試失敗：${r?.result?.status||"未知錯誤"}。`,ok?(disabled?"":"success"):"error");}catch(e){showError(e);}finally{busy=false;render();}}
async function clearOperation(i){profile.operations[i]={slot:i,element:null,value:""};await saveProfile();render();status($("setupStatus"),`已清除第 ${i+1} 組設定。`);}
async function executeOne(i){const item=profile.operations[i];if(!item.element||busy)return;try{busy=true;render();status($("operationStatus"),`正在執行第 ${i+1} 組...`);await ensureContent(target.tabId);const testOp=await chrome.tabs.sendMessage(target.tabId,{type:"TEST_LOCATOR",locator:item.element});const testSubmit=await chrome.tabs.sendMessage(target.tabId,{type:"TEST_LOCATOR",locator:profile.submit});if(testOp?.result?.status!=="valid")throw Error(`操作元素定位失敗：${testOp?.result?.status}`);if(testSubmit?.result?.status!=="valid")throw Error(`送出按鈕定位失敗：${testSubmit?.result?.status}`);const r=await chrome.tabs.sendMessage(target.tabId,{type:"EXECUTE_OPERATION",operation:item.element,value:item.value,executionId:crypto.randomUUID()});if(r?.result?.status!=="success")throw Error(`操作未完成：${r?.result?.status||"未知錯誤"}`);await focusSubmit(false);status($("operationStatus"),`第 ${i+1} 組執行成功，已跳到送出按鈕。`,"success");}catch(e){status($("operationStatus"),e.message||String(e),"error");}finally{busy=false;render();}}
async function focusSubmit(setBusy=true){if(!profile?.submit)return;try{if(setBusy){busy=true;render();status($("operationStatus"),"正在跳到送出按鈕...");}const tab=await chrome.tabs.get(target.tabId);await chrome.windows.update(tab.windowId,{focused:true});await chrome.tabs.update(tab.id,{active:true});await ensureContent(tab.id);const r=await chrome.tabs.sendMessage(tab.id,{type:"FOCUS_SUBMIT",submit:profile.submit,waitForEnable:!setBusy});if(r?.result?.status!=="focused")throw Error(r?.result?.status==="disabled"?"操作已完成，但送出按鈕仍未啟用。":`無法跳到送出按鈕：${r?.result?.status||"未知錯誤"}`);if(setBusy)status($("operationStatus"),"已跳到送出按鈕。若焦點仍在側邊欄，請按 F6。","success");}finally{if(setBusy){busy=false;render();}}}

async function refreshPage(){
  if(!targetReady()||busy)return;
  try{
    busy=true;render();status($("operationStatus"),"正在刷新目標網頁...");
    await chrome.tabs.reload(target.tabId);
    status($("operationStatus"),"目標網頁重新載入中，完成後會自動恢復操作。","success");
  }catch(e){status($("operationStatus"),e?.message||String(e),"error");}
  finally{busy=false;render();}
}
function showError(e){status($("setupStatus"),e?.message||String(e),"error");console.error(e);}
$("cancelSelectionButton").addEventListener("click",cancelSelection);document.addEventListener("keydown",event=>{if(event.key==="Escape"&&selecting){event.preventDefault();cancelSelection();}});$("refreshPageButton").addEventListener("click",refreshPage);$("setTargetButton").addEventListener("click",setTarget);$("clearTargetButton").addEventListener("click",clearTarget);$("selectSubmitButton").addEventListener("click",startSelectSubmit);$("testSubmitButton").addEventListener("click",()=>testLocator(profile.submit));$("focusSubmitButton").addEventListener("click",()=>focusSubmit(true).catch(e=>status($("operationStatus"),e.message,"error")));$("toggleSetupButton").addEventListener("click",()=>{$("setupSection").hidden=!$("setupSection").hidden;$("toggleSetupButton").textContent=$("setupSection").hidden?"設定":"收合";});$("finishSetupButton").addEventListener("click",()=>{$("setupSection").hidden=true;$("toggleSetupButton").textContent="設定";status($("operationStatus"),"設定完成，可選擇任一互斥操作方案。","success");});
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m.type==="OPERATION_SELECTED"){const p=m.payload;if(profile&&Number.isInteger(p.slotIndex)){profile.operations[p.slotIndex]={slot:p.slotIndex,element:{id:p.id,name:p.name,kind:p.kind,selector:p.selector,options:p.options||[]},value:["increment","decrement"].includes(p.kind)?"1":""};saveProfile().then(()=>{busy=false;selecting=null;render();status($("setupStatus"),`第 ${p.slotIndex+1} 組已設定為「${p.name}」。`,"success");reply({success:true});});return true;}}if(m.type==="SUBMIT_SELECTED"){profile.submit={id:m.payload.id,name:m.payload.name,kind:m.payload.kind,selector:m.payload.selector,disabledAtSelection:m.payload.disabledAtSelection===true};saveProfile().then(()=>{busy=false;selecting=null;render();status($("setupStatus"),`已設定送出按鈕「${m.payload.name}」。`,"success");reply({success:true});});return true;}if(m.type==="SELECTION_CANCELLED"){busy=false;selecting=null;render();status($("setupStatus"),"已取消框選。");}if(m.type==="TARGET_CHANGED"){target=m.payload.target;loadProfile().then(render);}});
loadTarget().catch(showError);
